services:
  prowlarr:
    image: 'lscr.io/linuxserver/prowlarr:latest'
    environment:
      - SERVICE_FQDN_PROWLARR_9696
      - _APP_URL=$SERVICE_FQDN_PROWLARR
      - PUID=1000
      - PGID=1000
      - 'TZ=${TZ:-Asia/Kolkata}'
    volumes:
      - 'prowlarr-config:/config'
    networks:
      - media-net
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:9696/ping'
      interval: 2s
      timeout: 10s
      retries: 15
  radarr:
    image: 'lscr.io/linuxserver/radarr:latest'
    environment:
      - SERVICE_FQDN_RADARR_7878
      - _APP_URL=$SERVICE_FQDN_RADARR
      - PUID=1000
      - PGID=1000
      - 'TZ=${TZ:-Asia/Kolkata}'
    volumes:
      - 'radarr-config:/config'
      - 'shared-media:/downloads'
      - 'shared-movies:/data/movies'
    networks:
      - media-net
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:7878/ping'
      interval: 2s
      timeout: 10s
      retries: 15
  sonarr:
    image: 'lscr.io/linuxserver/sonarr:latest'
    environment:
      - SERVICE_FQDN_SONARR_8989
      - _APP_URL=$SERVICE_FQDN_SONARR
      - PUID=1000
      - PGID=1000
      - 'TZ=${TZ:-America/Toronto}'
    volumes:
      - 'sonarr-config:/config'
      - 'shared-media:/downloads'
      - 'shared-tvshows:/data/tvshows'
    networks:
      - media-net
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:8989/ping'
      interval: 2s
      timeout: 10s
      retries: 15
  transmission:
    image: 'lscr.io/linuxserver/transmission:latest'
    environment:
      - SERVICE_FQDN_TRANSMISSION_9091
      - PUID=1000
      - PGID=1000
      - 'USER=${SERVICE_USER_ADMIN}'
      - 'PASS=${SERVICE_PASSWORD_ADMIN}'
    volumes:
      - 'transmission-config:/config'
      - 'shared-media:/downloads'
      - 'transmission-watch:/watch'
    networks:
      - media-net
    healthcheck:
      test:
        - CMD
        - curl
        - '-sSfL'
        - '-u'
        - '${SERVICE_USER_ADMIN}:${SERVICE_PASSWORD_ADMIN}'
        - 'http://localhost:9091/'
      interval: 30s
      timeout: 10s
      retries: 3
  jellyfin:
    image: 'lscr.io/linuxserver/jellyfin:latest'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - JELLYFIN_PublishedServerUrl=$SERVICE_FQDN_JELLYFIN
    volumes:
      - 'jellyfin-config:/config'
      - 'shared-media:/data/downloads'
      - 'shared-anime:/data/anime'
      - 'shared-movies:/data/movies'
      - 'shared-tvshows:/data/tvshows'
      - 'shared-webseries:/data/webseries'
    networks:
      - media-net
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:8096'
      interval: 2s
      timeout: 10s
      retries: 15
networks:
  media-net:
    driver: bridge
volumes:
  radarr-config: null
  sonarr-config: null
  transmission-config: null
  jellyfin-config: null
  transmission-watch: null
  shared-media: null
  shared-movies: null
  shared-tvshows: null
  shared-anime: null
  shared-webseries: null
